notifications:
  slack: 
    on_success: never
    on_failure: always
    rooms:
      - oicr:S9k4EowgQv9AnbCfEZHSzCsg

sudo: false
language: java
jdk: 
  - oraclejdk7
  - oraclejdk8

before_script: 
  - psql -c "create user queue_user with password 'queue' createdb;" -U postgres
  - psql -c "ALTER USER queue_user WITH superuser;" -U postgres
  - psql -c 'create database queue_status with owner = queue_user;' -U postgres
  - export PGPASSWORD='queue'; psql -h 127.0.0.1 -U queue_user  queue_status -f  pancancer-arch-3/sql/schema.sql
  - mkdir ~/.youxia
  - cp .travis/youxia_config ~/.youxia/config

script: 
  - mvn -B clean install -DskipITs=false
  - mvn -B clean -DskipITs=false cobertura:cobertura cobertura:cobertura-integration-test coveralls:report

addons:
  postgresql: "9.3"

services:
  - rabbitmq
