admin:
   build: .
   ports:
    - "8080:8080"
    - "8081:8081"
   links:
    - postgres
    - rabbitmq

postgres:
  image: postgres:9.4

rabbitmq:
  image: rabbitmq:3.5.6-management
  ports:
    - "15672:15672"
    - "5672:5672"
